package com.stark.studentmanagement.util;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.stark.studentmanagement.entity.User;
import org.springframework.stereotype.Component;

import java.io.FileOutputStream;

@Component
public class PdfService {
    
    public void generateAdmitCard(User user, String filePath) throws Exception {
        Document document = new Document(PageSize.A4);
        PdfWriter.getInstance(document, new FileOutputStream(filePath));
        document.open();
        
        // Add university header
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, BaseColor.DARK_GRAY);
        Paragraph title = new Paragraph("STARK UNIVERSITY", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);
        
        // Add separator
        document.add(new Paragraph(" "));
        document.add(new Paragraph(" "));
        
        // Add admit card title
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.BLACK);
        Paragraph header = new Paragraph("EXAMINATION ADMIT CARD", headerFont);
        header.setAlignment(Element.ALIGN_CENTER);
        document.add(header);
        
        document.add(new Paragraph(" "));
        document.add(new Paragraph(" "));
        
        // Add student details
        Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.BLACK);
        
        PdfPTable table = new PdfPTable(2);
        table.setWidthPercentage(60);
        table.setSpacingBefore(20f);
        table.setSpacingAfter(20f);
        
        table.addCell(createCell("Student Name:", normalFont, true));
        table.addCell(createCell(user.getFullName(), normalFont, false));
        
        table.addCell(createCell("ERP ID:", normalFont, true));
        table.addCell(createCell(user.getErpId(), normalFont, false));
        
        table.addCell(createCell("Department:", normalFont, true));
        table.addCell(createCell(user.getDepartment(), normalFont, false));
        
        table.addCell(createCell("Year:", normalFont, true));
        table.addCell(createCell(user.getYear() != null ? user.getYear().toString() : "N/A", normalFont, false));
        
        table.addCell(createCell("Section:", normalFont, true));
        table.addCell(createCell(user.getSection() != null ? user.getSection() : "N/A", normalFont, false));
        
        document.add(table);
        
        document.add(new Paragraph(" "));
        document.add(new Paragraph(" "));
        
        // Add instructions
        Font instructionFont = FontFactory.getFont(FontFactory.HELVETICA, 11, BaseColor.DARK_GRAY);
        Paragraph instructions = new Paragraph("INSTRUCTIONS:", instructionFont);
        instructions.setAlignment(Element.ALIGN_LEFT);
        document.add(instructions);
        
        document.add(new Paragraph("1. Carry this admit card to the examination hall.", instructionFont));
        document.add(new Paragraph("2. Bring a valid photo ID proof.", instructionFont));
        document.add(new Paragraph("3. Report 30 minutes before the exam time.", instructionFont));
        document.add(new Paragraph("4. Electronic devices are strictly prohibited.", instructionFont));
        document.add(new Paragraph("5. Follow all examination rules and regulations.", instructionFont));
        
        document.add(new Paragraph(" "));
        document.add(new Paragraph(" "));
        
        // Add footer
        Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.GRAY);
        Paragraph footer = new Paragraph("Generated by Student Management System", footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);
        
        document.close();
    }
    
    private PdfPCell createCell(String text, Font font, boolean isBold) {
        PdfPCell cell = new PdfPCell(new Phrase(text, isBold ? FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12) : font));
        cell.setBorder(Rectangle.NO_BORDER);
        cell.setPadding(5);
        return cell;
    }
}
